language: python
python:
 - "2.6"
 - "2.7"
# Someday, soon.
# - "3.2"
# - "3.3"
install: python setup.py install
script: python setup.py test
notifications:
    email: false
    irc:
        - "irc.freenode.net#eventray"
    on_success: change
    on_failure: change
